name: CI for Angular App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install --force

      - name: Lint code
        run: npm run lint

      - name: Commit after lint
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto lint CI

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install --force

      - name: Build the application
        run: npm run build --if-present

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install --force

      - name: Run unit tests with coverage
        run: npm run test -- --watch=false --code-coverage --browsers=ChromeHeadless

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/know-base-frontend/index.html

  coverage-report:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Display coverage
        run: |
          echo "Coverage results:"
          echo "1. Statements: $(grep -oP '<span class="strong">(\d+\.\d+%) </span>' coverage/know-base-frontend/index.html | sed -E 's/<span class="strong">([0-9.]+%) <\/span>/\1/' | sed -n '1p')"
          echo "2. Branches: $(grep -oP '<span class="strong">(\d+\.\d+%) </span>' coverage/know-base-frontend/index.html | sed -E 's/<span class="strong">([0-9.]+%) <\/span>/\1/' | sed -n '2p')"
          echo "3. Functions: $(grep -oP '<span class="strong">(\d+\.\d+%) </span>' coverage/know-base-frontend/index.html | sed -E 's/<span class="strong">([0-9.]+%) <\/span>/\1/' | sed -n '3p')"
          echo "4. Lines: $(grep -oP '<span class="strong">(\d+\.\d+%) </span>' coverage/know-base-frontend/index.html | sed -E 's/<span class="strong">([0-9.]+%) <\/span>/\1/' | sed -n '4p')"
